"""add delivery partner table

Revision ID: 2418d5f6452b
Revises: c5c737c85dc1
Create Date: 2026-05-09 22:11:26.471786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2418d5f6452b'
down_revision: Union[str, Sequence[str], None] = 'c5c737c85dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password_hash',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              nullable=True),
                    sa.Column('serviceable_zip_codes', sa.ARRAY(
                        sa.INTEGER()), nullable=True),
                    sa.Column('max_handling_capacity',
                              sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('seller', sa.Column(
        'created_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('seller', 'address')
    op.add_column('shipment', sa.Column(
        'created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column(
        'delivery_partner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', [
                          'delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shipment_seller_id_fkey',
                       'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('shipment', 'created_at')
    op.add_column('seller', sa.Column('address', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.drop_column('seller', 'created_at')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
