"""add client's contacts to a shipment model

Revision ID: 376aec693982
Revises: 9550427ba951
Create Date: 2026-05-12 04:11:10.649720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '376aec693982'
down_revision: Union[str, Sequence[str], None] = '9550427ba951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment', sa.Column('cleint_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'cleint_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
